// Static UUIDs for deterministic seeding (prefix fuse0000- for easy identification)

// ── Partner Profile IDs ──────────────────────────────────────────────
export const PARTNER_PROFILE_IDS = {
  TECH: 'fuse0000-0001-4000-8000-000000000001',
  CHANNEL: 'fuse0000-0001-4000-8000-000000000002',
  STRATEGIC: 'fuse0000-0001-4000-8000-000000000003',
} as const;

// ── Partner Track IDs ────────────────────────────────────────────────
export const PARTNER_TRACK_IDS = {
  SAAS_INTEGRATION: 'fuse0000-0002-4000-8000-000000000001',
  CHANNEL_PARTNER: 'fuse0000-0002-4000-8000-000000000002',
} as const;

// ── Track Check IDs ──────────────────────────────────────────────────
export const TRACK_CHECK_IDS = {
  T1_CHECK_1: 'fuse0000-0003-4000-8000-000000000001',
  T1_CHECK_2: 'fuse0000-0003-4000-8000-000000000002',
  T1_CHECK_3: 'fuse0000-0003-4000-8000-000000000003',
  T1_CHECK_4: 'fuse0000-0003-4000-8000-000000000004',
  T2_CHECK_1: 'fuse0000-0003-4000-8000-000000000005',
  T2_CHECK_2: 'fuse0000-0003-4000-8000-000000000006',
  T2_CHECK_3: 'fuse0000-0003-4000-8000-000000000007',
  T2_CHECK_4: 'fuse0000-0003-4000-8000-000000000008',
} as const;

// ── Discovery Run IDs ────────────────────────────────────────────────
export const DISCOVERY_RUN_IDS = {
  RUN_1: 'fuse0000-0004-4000-8000-000000000001',
} as const;

// ── Partner Candidate IDs ────────────────────────────────────────────
export const PARTNER_CANDIDATE_IDS = {
  C1: 'fuse0000-0005-4000-8000-000000000001',
  C2: 'fuse0000-0005-4000-8000-000000000002',
  C3: 'fuse0000-0005-4000-8000-000000000003',
  C4: 'fuse0000-0005-4000-8000-000000000004',
  C5: 'fuse0000-0005-4000-8000-000000000005',
  C6: 'fuse0000-0005-4000-8000-000000000006',
  C7: 'fuse0000-0005-4000-8000-000000000007',
  C8: 'fuse0000-0005-4000-8000-000000000008',
} as const;

// ── Partner Customer Map IDs ─────────────────────────────────────────
export const PARTNER_CUSTOMER_MAP_IDS = {
  M1: 'fuse0000-0006-4000-8000-000000000001',
  M2: 'fuse0000-0006-4000-8000-000000000002',
  M3: 'fuse0000-0006-4000-8000-000000000003',
} as const;

// ── Lead IDs ─────────────────────────────────────────────────────────
export const LEAD_IDS = {
  L1: 'fuse0000-0007-4000-8000-000000000001',
  L2: 'fuse0000-0007-4000-8000-000000000002',
  L3: 'fuse0000-0007-4000-8000-000000000003',
  L4: 'fuse0000-0007-4000-8000-000000000004',
} as const;

// ── Partner Attribution Event IDs ────────────────────────────────────
export const PARTNER_ATTRIBUTION_EVENT_IDS = {
  E1: 'fuse0000-0008-4000-8000-000000000001',
  E2: 'fuse0000-0008-4000-8000-000000000002',
} as const;

// ── Seed record arrays ──────────────────────────────────────────────

const now = new Date().toISOString();

export type SeedTableConfig = {
  tableName: string;
  columns: string[];
  records: Record<string, unknown>[];
};

export const PARTNER_OS_SEED_TABLES: SeedTableConfig[] = [
  // ── Partner Profiles ───────────────────────────────────────────
  {
    tableName: '_partnerProfile',
    columns: [
      'id',
      'partnerType',
      'lifecycleStage',
      'status',
      'position',
      'createdAt',
      'updatedAt',
      'deletedAt',
    ],
    records: [
      {
        id: PARTNER_PROFILE_IDS.TECH,
        partnerType: 'INTEGRATION_TECH',
        lifecycleStage: 'ACTIVE',
        status: 'ACTIVE',
        position: 1.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_PROFILE_IDS.CHANNEL,
        partnerType: 'RESELLER_VAR',
        lifecycleStage: 'EVALUATING',
        status: 'ACTIVE',
        position: 2.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_PROFILE_IDS.STRATEGIC,
        partnerType: 'MARKETPLACE_COSELL',
        lifecycleStage: 'PROSPECT',
        status: 'ACTIVE',
        position: 3.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
    ],
  },

  // ── Partner Tracks ─────────────────────────────────────────────
  {
    tableName: '_partnerTrack',
    columns: [
      'id',
      'name',
      'partnerType',
      'entityType',
      'outcome',
      'isTemplate',
      'outreachAngle',
      'position',
      'createdAt',
      'updatedAt',
      'deletedAt',
    ],
    records: [
      {
        id: PARTNER_TRACK_IDS.SAAS_INTEGRATION,
        name: 'SaaS Integration Discovery',
        partnerType: 'INTEGRATION_TECH',
        entityType: 'COMPANY',
        outcome: 'GROW_USAGE',
        isTemplate: true,
        outreachAngle:
          'We noticed your product complements our platform. Lets explore an integration.',
        position: 1.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_TRACK_IDS.CHANNEL_PARTNER,
        name: 'Channel Partner Search',
        partnerType: 'RESELLER_VAR',
        entityType: 'COMPANY',
        outcome: 'GROW_REVENUE',
        isTemplate: true,
        outreachAngle:
          'Your agency serves our ICP. Could a reseller partnership help your clients?',
        position: 2.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
    ],
  },

  // ── Track Checks (4 per track) ─────────────────────────────────
  {
    tableName: '_trackCheck',
    columns: [
      'id',
      'checkLabel',
      'prompt',
      'weight',
      'gateMode',
      'position',
      'partnerTrackId',
      'createdAt',
      'updatedAt',
      'deletedAt',
    ],
    records: [
      // Track 1 checks
      {
        id: TRACK_CHECK_IDS.T1_CHECK_1,
        checkLabel: 'Has REST API',
        prompt:
          'Does the company offer a publicly documented REST or GraphQL API?',
        weight: 30,
        gateMode: 'MUST_PASS',
        position: 1.0,
        partnerTrackId: PARTNER_TRACK_IDS.SAAS_INTEGRATION,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: TRACK_CHECK_IDS.T1_CHECK_2,
        checkLabel: 'Monthly traffic > 10k',
        prompt:
          'Does the company website receive more than 10,000 monthly visits?',
        weight: 20,
        gateMode: 'SIGNAL',
        position: 2.0,
        partnerTrackId: PARTNER_TRACK_IDS.SAAS_INTEGRATION,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: TRACK_CHECK_IDS.T1_CHECK_3,
        checkLabel: 'SOC2 certified',
        prompt:
          'Is the company SOC2 Type II certified or equivalent (ISO 27001)?',
        weight: 25,
        gateMode: 'SIGNAL',
        position: 3.0,
        partnerTrackId: PARTNER_TRACK_IDS.SAAS_INTEGRATION,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: TRACK_CHECK_IDS.T1_CHECK_4,
        checkLabel: 'Active developer community',
        prompt:
          'Does the company have an active developer community (GitHub, Discord, forum)?',
        weight: 25,
        gateMode: 'SIGNAL',
        position: 4.0,
        partnerTrackId: PARTNER_TRACK_IDS.SAAS_INTEGRATION,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      // Track 2 checks
      {
        id: TRACK_CHECK_IDS.T2_CHECK_1,
        checkLabel: 'Serves SMB segment',
        prompt:
          'Does the agency primarily serve small and mid-market businesses?',
        weight: 30,
        gateMode: 'MUST_PASS',
        position: 1.0,
        partnerTrackId: PARTNER_TRACK_IDS.CHANNEL_PARTNER,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: TRACK_CHECK_IDS.T2_CHECK_2,
        checkLabel: 'CRM consulting experience',
        prompt:
          'Does the agency have demonstrated CRM implementation or consulting experience?',
        weight: 25,
        gateMode: 'SIGNAL',
        position: 2.0,
        partnerTrackId: PARTNER_TRACK_IDS.CHANNEL_PARTNER,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: TRACK_CHECK_IDS.T2_CHECK_3,
        checkLabel: 'Active customer base > 50',
        prompt: 'Does the agency have more than 50 active client accounts?',
        weight: 20,
        gateMode: 'SIGNAL',
        position: 3.0,
        partnerTrackId: PARTNER_TRACK_IDS.CHANNEL_PARTNER,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: TRACK_CHECK_IDS.T2_CHECK_4,
        checkLabel: 'Located in target geo',
        prompt:
          'Is the agency headquartered in North America or Western Europe?',
        weight: 25,
        gateMode: 'SIGNAL',
        position: 4.0,
        partnerTrackId: PARTNER_TRACK_IDS.CHANNEL_PARTNER,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
    ],
  },

  // ── Discovery Run ──────────────────────────────────────────────
  {
    tableName: '_discoveryRun',
    columns: [
      'id',
      'queryRaw',
      'queryOptimized',
      'status',
      'resultCount',
      'startedAt',
      'completedAt',
      'partnerTrackId',
      'position',
      'createdAt',
      'updatedAt',
      'deletedAt',
    ],
    records: [
      {
        id: DISCOVERY_RUN_IDS.RUN_1,
        queryRaw: 'SaaS companies with public REST APIs and developer programs',
        queryOptimized:
          'B2B SaaS companies with documented REST API, active developer community, SOC2 certified',
        status: 'COMPLETE',
        resultCount: 8,
        startedAt: new Date(Date.now() - 3600000).toISOString(),
        completedAt: now,
        partnerTrackId: PARTNER_TRACK_IDS.SAAS_INTEGRATION,
        position: 1.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
    ],
  },

  // ── Partner Candidates (8 total) ───────────────────────────────
  {
    tableName: '_partnerCandidate',
    columns: [
      'id',
      'entityUrl',
      'entityType',
      'displayName',
      'companyDomain',
      'fitScore',
      'confidence',
      'gateStatus',
      'gateReason',
      'receivedAt',
      'discoveryRunId',
      'position',
      'createdAt',
      'updatedAt',
      'deletedAt',
    ],
    records: [
      {
        id: PARTNER_CANDIDATE_IDS.C1,
        entityUrl: 'https://zapier.com',
        entityType: 'COMPANY',
        displayName: 'Zapier',
        companyDomain: 'zapier.com',
        fitScore: 92,
        confidence: 88,
        gateStatus: 'QUALIFIED',
        gateReason: null,
        receivedAt: now,
        discoveryRunId: DISCOVERY_RUN_IDS.RUN_1,
        position: 1.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_CANDIDATE_IDS.C2,
        entityUrl: 'https://segment.com',
        entityType: 'COMPANY',
        displayName: 'Segment',
        companyDomain: 'segment.com',
        fitScore: 87,
        confidence: 91,
        gateStatus: 'QUALIFIED',
        gateReason: null,
        receivedAt: now,
        discoveryRunId: DISCOVERY_RUN_IDS.RUN_1,
        position: 2.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_CANDIDATE_IDS.C3,
        entityUrl: 'https://calendly.com',
        entityType: 'COMPANY',
        displayName: 'Calendly',
        companyDomain: 'calendly.com',
        fitScore: 78,
        confidence: 82,
        gateStatus: 'QUALIFIED',
        gateReason: null,
        receivedAt: now,
        discoveryRunId: DISCOVERY_RUN_IDS.RUN_1,
        position: 3.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_CANDIDATE_IDS.C4,
        entityUrl: 'https://notion.so',
        entityType: 'COMPANY',
        displayName: 'Notion',
        companyDomain: 'notion.so',
        fitScore: 74,
        confidence: 79,
        gateStatus: 'QUALIFIED',
        gateReason: null,
        receivedAt: now,
        discoveryRunId: DISCOVERY_RUN_IDS.RUN_1,
        position: 4.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_CANDIDATE_IDS.C5,
        entityUrl: 'https://airtable.com',
        entityType: 'COMPANY',
        displayName: 'Airtable',
        companyDomain: 'airtable.com',
        fitScore: 68,
        confidence: 75,
        gateStatus: 'QUALIFIED',
        gateReason: null,
        receivedAt: now,
        discoveryRunId: DISCOVERY_RUN_IDS.RUN_1,
        position: 5.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_CANDIDATE_IDS.C6,
        entityUrl: 'https://freshworks.com',
        entityType: 'COMPANY',
        displayName: 'Freshworks',
        companyDomain: 'freshworks.com',
        fitScore: 45,
        confidence: 62,
        gateStatus: 'DISQUALIFIED',
        gateReason: 'Competitor in CRM space — fails must-pass gate',
        receivedAt: now,
        discoveryRunId: DISCOVERY_RUN_IDS.RUN_1,
        position: 6.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_CANDIDATE_IDS.C7,
        entityUrl: 'https://lemlist.com',
        entityType: 'COMPANY',
        displayName: 'Lemlist',
        companyDomain: 'lemlist.com',
        fitScore: 55,
        confidence: 70,
        gateStatus: 'EXCLUDED',
        gateReason: 'Already an active partner — excluded by track rule',
        receivedAt: now,
        discoveryRunId: DISCOVERY_RUN_IDS.RUN_1,
        position: 7.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_CANDIDATE_IDS.C8,
        entityUrl: 'https://typeform.com',
        entityType: 'COMPANY',
        displayName: 'Typeform',
        companyDomain: 'typeform.com',
        fitScore: 71,
        confidence: 77,
        gateStatus: 'QUALIFIED',
        gateReason: null,
        receivedAt: now,
        discoveryRunId: DISCOVERY_RUN_IDS.RUN_1,
        position: 8.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
    ],
  },

  // ── Partner Customer Maps ──────────────────────────────────────
  {
    tableName: '_partnerCustomerMap',
    columns: [
      'id',
      'mapStage',
      'motionType',
      'confidence',
      'partnerProfileId',
      'position',
      'createdAt',
      'updatedAt',
      'deletedAt',
    ],
    records: [
      {
        id: PARTNER_CUSTOMER_MAP_IDS.M1,
        mapStage: 'CO_SELL',
        motionType: 'INTEGRATION',
        confidence: 80,
        partnerProfileId: PARTNER_PROFILE_IDS.TECH,
        position: 1.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_CUSTOMER_MAP_IDS.M2,
        mapStage: 'MATCHED',
        motionType: 'REFERRAL',
        confidence: 60,
        partnerProfileId: PARTNER_PROFILE_IDS.CHANNEL,
        position: 2.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_CUSTOMER_MAP_IDS.M3,
        mapStage: 'IDENTIFIED',
        motionType: 'DISCOVERY',
        confidence: 40,
        partnerProfileId: PARTNER_PROFILE_IDS.STRATEGIC,
        position: 3.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
    ],
  },

  // ── Leads ──────────────────────────────────────────────────────
  {
    tableName: '_lead',
    columns: [
      'id',
      'sourceType',
      'status',
      'sourceDetail',
      'sourcePartnerProfileId',
      'position',
      'createdAt',
      'updatedAt',
      'deletedAt',
    ],
    records: [
      {
        id: LEAD_IDS.L1,
        sourceType: 'PARTNER_SOURCED',
        status: 'QUALIFYING',
        sourceDetail: 'Referred by tech partner during joint webinar',
        sourcePartnerProfileId: PARTNER_PROFILE_IDS.TECH,
        position: 1.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: LEAD_IDS.L2,
        sourceType: 'INBOUND',
        status: 'NEW',
        sourceDetail: 'Organic signup from partner co-marketing landing page',
        sourcePartnerProfileId: null,
        position: 2.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: LEAD_IDS.L3,
        sourceType: 'MANUAL',
        status: 'CONVERTED',
        sourceDetail: 'Added manually by partnerships team after conference',
        sourcePartnerProfileId: PARTNER_PROFILE_IDS.CHANNEL,
        position: 3.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: LEAD_IDS.L4,
        sourceType: 'IMPORT',
        status: 'DISQUALIFIED',
        sourceDetail: 'Bulk import from partner CRM export — low quality batch',
        sourcePartnerProfileId: PARTNER_PROFILE_IDS.STRATEGIC,
        position: 4.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
    ],
  },

  // ── Partner Attribution Events ─────────────────────────────────
  {
    tableName: '_partnerAttributionEvent',
    columns: [
      'id',
      'eventType',
      'occurredAt',
      'sourceObjectType',
      'sourceObjectId',
      'weightHint',
      'partnerProfileId',
      'position',
      'createdAt',
      'updatedAt',
      'deletedAt',
    ],
    records: [
      {
        id: PARTNER_ATTRIBUTION_EVENT_IDS.E1,
        eventType: 'SOURCED',
        occurredAt: new Date(Date.now() - 86400000 * 7).toISOString(),
        sourceObjectType: 'lead',
        sourceObjectId: LEAD_IDS.L1,
        weightHint: 100,
        partnerProfileId: PARTNER_PROFILE_IDS.TECH,
        position: 1.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
      {
        id: PARTNER_ATTRIBUTION_EVENT_IDS.E2,
        eventType: 'INFLUENCED',
        occurredAt: new Date(Date.now() - 86400000 * 3).toISOString(),
        sourceObjectType: 'lead',
        sourceObjectId: LEAD_IDS.L3,
        weightHint: 50,
        partnerProfileId: PARTNER_PROFILE_IDS.CHANNEL,
        position: 2.0,
        createdAt: now,
        updatedAt: now,
        deletedAt: null,
      },
    ],
  },
];
