import { FieldMetadataType, RelationType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';
import { type ObjectMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/object-metadata-seed.type';

export type PartnerOsRelationFieldSeed = {
  name: string;
  label: string;
  icon: string;
  targetObjectName: string;
  relationType: RelationType;
  targetFieldLabel: string;
  targetFieldIcon: string;
};

export type PartnerOsObjectSchema = {
  object: ObjectMetadataSeed;
  fields: FieldMetadataSeed[];
  relations: PartnerOsRelationFieldSeed[];
  kanbanFieldName?: string;
  calendarFieldName?: string;
};

const asSelectOptions = (...values: string[]) =>
  values.map((value, index) => ({
    value,
    label: value
      .toLowerCase()
      .replace(/_/g, ' ')
      .replace(/\b\w/g, (char) => char.toUpperCase()),
    color: [
      'sky',
      'green',
      'yellow',
      'orange',
      'red',
      'purple',
      'pink',
      'turquoise',
      'gray',
    ][index % 9],
    position: index,
  }));

export const PARTNER_OS_OBJECT_SCHEMAS: PartnerOsObjectSchema[] = [
  {
    object: {
      nameSingular: 'lead',
      namePlural: 'leads',
      labelSingular: 'Lead',
      labelPlural: 'Leads',
      description: 'Pre-conversion contact identity with partner lineage',
      icon: 'IconUserPlus',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.SELECT,
        name: 'sourceType',
        label: 'Source Type',
        icon: 'IconTargetArrow',
        options: asSelectOptions(
          'MANUAL',
          'PARTNER_SOURCED',
          'INBOUND',
          'IMPORT',
        ),
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'status',
        label: 'Status',
        icon: 'IconProgressCheck',
        options: asSelectOptions(
          'NEW',
          'QUALIFYING',
          'CONVERTED',
          'DISQUALIFIED',
        ),
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'sourceDetail',
        label: 'Source Detail',
        icon: 'IconTextCaption',
      },
      {
        type: FieldMetadataType.RICH_TEXT_V2,
        name: 'notes',
        label: 'Notes',
        icon: 'IconNotes',
      },
    ],
    relations: [
      {
        name: 'sourcePartnerProfile',
        label: 'Source Partner Profile',
        icon: 'IconBuildingSkyscraper',
        targetObjectName: 'partnerProfile',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Sourced Leads',
        targetFieldIcon: 'IconUsers',
      },
      {
        name: 'sourcePartnerPerson',
        label: 'Source Partner Person',
        icon: 'IconUser',
        targetObjectName: 'person',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Partner Sourced Leads',
        targetFieldIcon: 'IconUsers',
      },
      {
        name: 'convertedPerson',
        label: 'Converted Person',
        icon: 'IconUser',
        targetObjectName: 'person',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Converted Leads',
        targetFieldIcon: 'IconUsers',
      },
      {
        name: 'convertedCompany',
        label: 'Converted Company',
        icon: 'IconBuildingSkyscraper',
        targetObjectName: 'company',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Converted Leads',
        targetFieldIcon: 'IconUsers',
      },
      {
        name: 'convertedOpportunity',
        label: 'Converted Opportunity',
        icon: 'IconTargetArrow',
        targetObjectName: 'opportunity',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Converted Leads',
        targetFieldIcon: 'IconUsers',
      },
    ],
    kanbanFieldName: 'status',
  },
  {
    object: {
      nameSingular: 'partnerProfile',
      namePlural: 'partnerProfiles',
      labelSingular: 'Partner Profile',
      labelPlural: 'Partner Profiles',
      description: 'Partner role profile layered on top of a canonical company',
      icon: 'IconBuildingHandshake',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.SELECT,
        name: 'partnerType',
        label: 'Partner Type',
        icon: 'IconHierarchy3',
        options: asSelectOptions(
          'INTEGRATION_TECH',
          'AGENCY_SI',
          'AFFILIATE',
          'B2B_INFLUENCER_CREATOR',
          'RESELLER_VAR',
          'REFERRAL',
          'MARKETPLACE_COSELL',
        ),
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'lifecycleStage',
        label: 'Lifecycle Stage',
        icon: 'IconProgressCheck',
        options: asSelectOptions(
          'PROSPECT',
          'EVALUATING',
          'ACTIVE',
          'PAUSED',
          'TERMINATED',
        ),
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'status',
        label: 'Status',
        icon: 'IconToggleLeft',
        options: asSelectOptions('ACTIVE', 'INACTIVE', 'BLOCKED'),
      },
    ],
    relations: [
      {
        name: 'company',
        label: 'Company',
        icon: 'IconBuildingSkyscraper',
        targetObjectName: 'company',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Partner Profiles',
        targetFieldIcon: 'IconBuildingHandshake',
      },
      {
        name: 'owner',
        label: 'Owner',
        icon: 'IconUserCircle',
        targetObjectName: 'workspaceMember',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Owned Partner Profiles',
        targetFieldIcon: 'IconBuildingHandshake',
      },
    ],
    kanbanFieldName: 'lifecycleStage',
  },
  {
    object: {
      nameSingular: 'partnerContactAssignment',
      namePlural: 'partnerContactAssignments',
      labelSingular: 'Partner Contact Assignment',
      labelPlural: 'Partner Contact Assignments',
      description: 'Contextual role of a person in a partner profile',
      icon: 'IconUserBolt',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.TEXT,
        name: 'partnerRole',
        label: 'Role',
        icon: 'IconId',
      },
      {
        type: FieldMetadataType.BOOLEAN,
        name: 'isPrimary',
        label: 'Is Primary',
        icon: 'IconStar',
        defaultValue: false,
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'certificationStatus',
        label: 'Certification Status',
        icon: 'IconCertificate',
        options: asSelectOptions(
          'NOT_REQUIRED',
          'PENDING',
          'CERTIFIED',
          'EXPIRED',
        ),
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'notes',
        label: 'Notes',
        icon: 'IconNotes',
      },
    ],
    relations: [
      {
        name: 'partnerProfile',
        label: 'Partner Profile',
        icon: 'IconBuildingHandshake',
        targetObjectName: 'partnerProfile',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Contact Assignments',
        targetFieldIcon: 'IconUsers',
      },
      {
        name: 'person',
        label: 'Person',
        icon: 'IconUser',
        targetObjectName: 'person',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Partner Assignments',
        targetFieldIcon: 'IconUsers',
      },
    ],
  },
  {
    object: {
      nameSingular: 'partnerCustomerMap',
      namePlural: 'partnerCustomerMaps',
      labelSingular: 'Partner Customer Map',
      labelPlural: 'Partner Customer Maps',
      description: 'Mapping layer between partners and customer opportunities',
      icon: 'IconRouteAltLeft',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.SELECT,
        name: 'mapStage',
        label: 'Map Stage',
        icon: 'IconProgressCheck',
        options: asSelectOptions(
          'IDENTIFIED',
          'MATCHED',
          'INTRODUCED',
          'CO_SELL',
          'CLOSED_WON',
          'CLOSED_LOST',
        ),
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'motionType',
        label: 'Motion Type',
        icon: 'IconGitBranch',
        options: asSelectOptions(
          'DISCOVERY',
          'REFERRAL',
          'CO_SELL',
          'INTEGRATION',
          'MARKETPLACE',
        ),
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'confidence',
        label: 'Confidence',
        icon: 'IconPercentage',
      },
    ],
    relations: [
      {
        name: 'partnerProfile',
        label: 'Partner Profile',
        icon: 'IconBuildingHandshake',
        targetObjectName: 'partnerProfile',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Customer Maps',
        targetFieldIcon: 'IconRouteAltLeft',
      },
      {
        name: 'customerCompany',
        label: 'Customer Company',
        icon: 'IconBuildingSkyscraper',
        targetObjectName: 'company',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Partner Customer Maps',
        targetFieldIcon: 'IconRouteAltLeft',
      },
      {
        name: 'opportunity',
        label: 'Opportunity',
        icon: 'IconTargetArrow',
        targetObjectName: 'opportunity',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Partner Customer Maps',
        targetFieldIcon: 'IconRouteAltLeft',
      },
      {
        name: 'owner',
        label: 'Owner',
        icon: 'IconUserCircle',
        targetObjectName: 'workspaceMember',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Owned Partner Customer Maps',
        targetFieldIcon: 'IconRouteAltLeft',
      },
    ],
    kanbanFieldName: 'mapStage',
  },
  {
    object: {
      nameSingular: 'partnerAttributionEvent',
      namePlural: 'partnerAttributionEvents',
      labelSingular: 'Partner Attribution Event',
      labelPlural: 'Partner Attribution Events',
      description: 'Immutable attribution touchpoint event',
      icon: 'IconClockHour4',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.SELECT,
        name: 'eventType',
        label: 'Event Type',
        icon: 'IconTargetArrow',
        options: asSelectOptions(
          'SOURCED',
          'INFLUENCED',
          'INTRODUCED',
          'ASSISTED',
          'TOUCHPOINT',
        ),
      },
      {
        type: FieldMetadataType.DATE_TIME,
        name: 'occurredAt',
        label: 'Occurred At',
        icon: 'IconCalendarTime',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'sourceObjectType',
        label: 'Source Object Type',
        icon: 'IconDatabase',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'sourceObjectId',
        label: 'Source Object ID',
        icon: 'IconHash',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'weightHint',
        label: 'Weight Hint',
        icon: 'IconPercentage',
      },
      {
        type: FieldMetadataType.RAW_JSON,
        name: 'evidence',
        label: 'Evidence',
        icon: 'IconFileDescription',
      },
    ],
    relations: [
      {
        name: 'partnerProfile',
        label: 'Partner Profile',
        icon: 'IconBuildingHandshake',
        targetObjectName: 'partnerProfile',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Attribution Events',
        targetFieldIcon: 'IconClockHour4',
      },
      {
        name: 'customerCompany',
        label: 'Customer Company',
        icon: 'IconBuildingSkyscraper',
        targetObjectName: 'company',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Partner Attribution Events',
        targetFieldIcon: 'IconClockHour4',
      },
      {
        name: 'opportunity',
        label: 'Opportunity',
        icon: 'IconTargetArrow',
        targetObjectName: 'opportunity',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Partner Attribution Events',
        targetFieldIcon: 'IconClockHour4',
      },
    ],
    calendarFieldName: 'occurredAt',
  },
  {
    object: {
      nameSingular: 'partnerAttributionSnapshot',
      namePlural: 'partnerAttributionSnapshots',
      labelSingular: 'Partner Attribution Snapshot',
      labelPlural: 'Partner Attribution Snapshots',
      description: 'Materialized attribution snapshot for reporting',
      icon: 'IconChartHistogram',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.SELECT,
        name: 'model',
        label: 'Model',
        icon: 'IconHierarchy2',
        options: asSelectOptions(
          'FIRST_TOUCH',
          'LAST_TOUCH',
          'LINEAR',
          'CUSTOM_WEIGHTED',
        ),
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'lookbackWindowDays',
        label: 'Lookback Window Days',
        icon: 'IconCalendarStats',
      },
      {
        type: FieldMetadataType.DATE,
        name: 'periodStart',
        label: 'Period Start',
        icon: 'IconCalendarEvent',
      },
      {
        type: FieldMetadataType.DATE,
        name: 'periodEnd',
        label: 'Period End',
        icon: 'IconCalendarEvent',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'creditedRevenue',
        label: 'Credited Revenue',
        icon: 'IconCoins',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'creditPercent',
        label: 'Credit Percent',
        icon: 'IconPercentage',
      },
    ],
    relations: [
      {
        name: 'partnerProfile',
        label: 'Partner Profile',
        icon: 'IconBuildingHandshake',
        targetObjectName: 'partnerProfile',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Attribution Snapshots',
        targetFieldIcon: 'IconChartHistogram',
      },
      {
        name: 'customerCompany',
        label: 'Customer Company',
        icon: 'IconBuildingSkyscraper',
        targetObjectName: 'company',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Partner Attribution Snapshots',
        targetFieldIcon: 'IconChartHistogram',
      },
      {
        name: 'opportunity',
        label: 'Opportunity',
        icon: 'IconTargetArrow',
        targetObjectName: 'opportunity',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Partner Attribution Snapshots',
        targetFieldIcon: 'IconChartHistogram',
      },
    ],
  },
  {
    object: {
      nameSingular: 'customerEvent',
      namePlural: 'customerEvents',
      labelSingular: 'Customer Event',
      labelPlural: 'Customer Events',
      description: 'Append-only customer revenue and pipeline event ledger',
      icon: 'IconClockHour4',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.SELECT,
        name: 'eventType',
        label: 'Event Type',
        icon: 'IconBolt',
        options: asSelectOptions(
          'OPPORTUNITY_CREATED',
          'OPPORTUNITY_STAGE_CHANGED',
          'OPPORTUNITY_CLOSED_WON',
          'OPPORTUNITY_CLOSED_LOST',
          'PARTNER_MENTIONED',
          'PARTNER_INTRODUCED',
          'PARTNER_ASSISTED',
        ),
      },
      {
        type: FieldMetadataType.DATE_TIME,
        name: 'occurredAt',
        label: 'Occurred At',
        icon: 'IconCalendarTime',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'eventValue',
        label: 'Event Value',
        icon: 'IconCoins',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'currencyCode',
        label: 'Currency Code',
        icon: 'IconTextCaption',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'sourceObjectType',
        label: 'Source Object Type',
        icon: 'IconDatabase',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'sourceObjectId',
        label: 'Source Object ID',
        icon: 'IconHash',
      },
      {
        type: FieldMetadataType.RAW_JSON,
        name: 'details',
        label: 'Details',
        icon: 'IconFileDescription',
      },
    ],
    relations: [
      {
        name: 'customerCompany',
        label: 'Customer Company',
        icon: 'IconBuildingSkyscraper',
        targetObjectName: 'company',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Customer Events',
        targetFieldIcon: 'IconClockHour4',
      },
      {
        name: 'opportunity',
        label: 'Opportunity',
        icon: 'IconTargetArrow',
        targetObjectName: 'opportunity',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Customer Events',
        targetFieldIcon: 'IconClockHour4',
      },
      {
        name: 'partnerProfile',
        label: 'Partner Profile',
        icon: 'IconBuildingHandshake',
        targetObjectName: 'partnerProfile',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Customer Events',
        targetFieldIcon: 'IconClockHour4',
      },
      {
        name: 'partnerCustomerMap',
        label: 'Partner Customer Map',
        icon: 'IconRouteAltLeft',
        targetObjectName: 'partnerCustomerMap',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Customer Events',
        targetFieldIcon: 'IconClockHour4',
      },
    ],
    calendarFieldName: 'occurredAt',
  },
  {
    object: {
      nameSingular: 'customerSnapshot',
      namePlural: 'customerSnapshots',
      labelSingular: 'Customer Snapshot',
      labelPlural: 'Customer Snapshots',
      description: 'Materialized customer pipeline and revenue rollup',
      icon: 'IconChartHistogram',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.SELECT,
        name: 'model',
        label: 'Model',
        icon: 'IconHierarchy2',
        options: asSelectOptions(
          'FIRST_TOUCH',
          'LAST_TOUCH',
          'LINEAR',
          'CUSTOM_WEIGHTED',
        ),
      },
      {
        type: FieldMetadataType.DATE,
        name: 'periodStart',
        label: 'Period Start',
        icon: 'IconCalendarEvent',
      },
      {
        type: FieldMetadataType.DATE,
        name: 'periodEnd',
        label: 'Period End',
        icon: 'IconCalendarEvent',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'openPipelineAmount',
        label: 'Open Pipeline Amount',
        icon: 'IconChartArrows',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'sourcedRevenueAmount',
        label: 'Sourced Revenue Amount',
        icon: 'IconCoins',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'influencedRevenueAmount',
        label: 'Influenced Revenue Amount',
        icon: 'IconCoins',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'wonRevenueAmount',
        label: 'Won Revenue Amount',
        icon: 'IconCoins',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'activeOpportunityCount',
        label: 'Active Opportunity Count',
        icon: 'IconListNumbers',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'wonOpportunityCount',
        label: 'Won Opportunity Count',
        icon: 'IconListNumbers',
      },
      {
        type: FieldMetadataType.DATE_TIME,
        name: 'generatedAt',
        label: 'Generated At',
        icon: 'IconCalendarTime',
      },
    ],
    relations: [
      {
        name: 'customerCompany',
        label: 'Customer Company',
        icon: 'IconBuildingSkyscraper',
        targetObjectName: 'company',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Customer Snapshots',
        targetFieldIcon: 'IconChartHistogram',
      },
      {
        name: 'partnerProfile',
        label: 'Partner Profile',
        icon: 'IconBuildingHandshake',
        targetObjectName: 'partnerProfile',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Customer Snapshots',
        targetFieldIcon: 'IconChartHistogram',
      },
      {
        name: 'partnerCustomerMap',
        label: 'Partner Customer Map',
        icon: 'IconRouteAltLeft',
        targetObjectName: 'partnerCustomerMap',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Customer Snapshots',
        targetFieldIcon: 'IconChartHistogram',
      },
    ],
    calendarFieldName: 'generatedAt',
  },
  {
    object: {
      nameSingular: 'partnerTrack',
      namePlural: 'partnerTracks',
      labelSingular: 'Partner Track',
      labelPlural: 'Partner Tracks',
      description:
        'Reusable discovery and partner execution template — one track per PartnerType x Outcome',
      icon: 'IconRoute',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.SELECT,
        name: 'partnerType',
        label: 'Partner Type',
        icon: 'IconHierarchy3',
        options: asSelectOptions(
          'INTEGRATION_TECH',
          'AGENCY_SI',
          'AFFILIATE',
          'B2B_INFLUENCER_CREATOR',
          'RESELLER_VAR',
          'REFERRAL',
          'MARKETPLACE_COSELL',
        ),
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'entityType',
        label: 'Entity Type',
        icon: 'IconUsersGroup',
        options: asSelectOptions('COMPANY', 'PERSON'),
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'outcome',
        label: 'Outcome',
        icon: 'IconTargetArrow',
        options: asSelectOptions(
          'GROW_REVENUE',
          'GROW_USAGE',
          'ENTER_MARKET',
          'REDUCE_CHURN',
          'EXPAND_SERVICES',
          'BRAND_AWARENESS',
        ),
      },
      {
        type: FieldMetadataType.BOOLEAN,
        name: 'isTemplate',
        label: 'Is Template',
        icon: 'IconTemplate',
        defaultValue: false,
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'outreachAngle',
        label: 'Outreach Angle',
        icon: 'IconMessage',
      },
      {
        type: FieldMetadataType.RAW_JSON,
        name: 'successMetrics',
        label: 'Success Metrics',
        icon: 'IconTargetArrow',
      },
    ],
    relations: [
      {
        name: 'owner',
        label: 'Owner',
        icon: 'IconUserCircle',
        targetObjectName: 'workspaceMember',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Owned Partner Tracks',
        targetFieldIcon: 'IconRoute',
      },
    ],
  },
  {
    object: {
      nameSingular: 'trackCheck',
      namePlural: 'trackChecks',
      labelSingular: 'Track Check',
      labelPlural: 'Track Checks',
      description: 'Retrieval check and fit signal definition for a track',
      icon: 'IconChecklist',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.TEXT,
        name: 'checkLabel',
        label: 'Check Label',
        icon: 'IconTextCaption',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'prompt',
        label: 'Prompt',
        icon: 'IconFileDescription',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'weight',
        label: 'Weight',
        icon: 'IconPercentage',
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'gateMode',
        label: 'Gate Mode',
        icon: 'IconFilter',
        options: asSelectOptions('SIGNAL', 'MUST_PASS'),
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'position',
        label: 'Position',
        icon: 'IconSortAscending',
      },
    ],
    relations: [
      {
        name: 'partnerTrack',
        label: 'Partner Track',
        icon: 'IconRoute',
        targetObjectName: 'partnerTrack',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Checks',
        targetFieldIcon: 'IconChecklist',
      },
    ],
  },
  {
    object: {
      nameSingular: 'trackEnrichment',
      namePlural: 'trackEnrichments',
      labelSingular: 'Track Enrichment',
      labelPlural: 'Track Enrichments',
      description: 'Enrichment column definition for a track',
      icon: 'IconTablePlus',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.TEXT,
        name: 'enrichmentName',
        label: 'Enrichment Name',
        icon: 'IconTextCaption',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'prompt',
        label: 'Prompt',
        icon: 'IconFileDescription',
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'format',
        label: 'Format',
        icon: 'IconBrackets',
        options: asSelectOptions(
          'TEXT',
          'NUMBER',
          'URL',
          'EMAIL',
          'PHONE',
          'OPTIONS',
        ),
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'position',
        label: 'Position',
        icon: 'IconSortAscending',
      },
    ],
    relations: [
      {
        name: 'partnerTrack',
        label: 'Partner Track',
        icon: 'IconRoute',
        targetObjectName: 'partnerTrack',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Enrichments',
        targetFieldIcon: 'IconTablePlus',
      },
    ],
  },
  {
    object: {
      nameSingular: 'trackExclusion',
      namePlural: 'trackExclusions',
      labelSingular: 'Track Exclusion',
      labelPlural: 'Track Exclusions',
      description: 'Exclusion rule scoped to a partner track',
      icon: 'IconFilterX',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.TEXT,
        name: 'identifier',
        label: 'Identifier',
        icon: 'IconHash',
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'exclusionType',
        label: 'Exclusion Type',
        icon: 'IconShieldX',
        options: asSelectOptions(
          'COMPETITOR',
          'DNC',
          'ACTIVE_PARTNER',
          'ALREADY_CONTACTED',
          'BAD_FIT',
          'ALREADY_DISPLAYED',
          'RESTRICTED',
        ),
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'reason',
        label: 'Reason',
        icon: 'IconNotes',
      },
    ],
    relations: [
      {
        name: 'partnerTrack',
        label: 'Partner Track',
        icon: 'IconRoute',
        targetObjectName: 'partnerTrack',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Exclusions',
        targetFieldIcon: 'IconFilterX',
      },
    ],
  },
  {
    object: {
      nameSingular: 'discoveryRun',
      namePlural: 'discoveryRuns',
      labelSingular: 'Discovery Run',
      labelPlural: 'Discovery Runs',
      description: 'Single webset-backed execution of a partner track',
      icon: 'IconPlayerPlay',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.TEXT,
        name: 'queryRaw',
        label: 'Query Raw',
        icon: 'IconMessageSearch',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'queryOptimized',
        label: 'Query Optimized',
        icon: 'IconSparkles',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'exaWebsetId',
        label: 'Exa Webset ID',
        icon: 'IconHash',
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'status',
        label: 'Status',
        icon: 'IconLoader',
        options: asSelectOptions(
          'PENDING',
          'STREAMING',
          'COMPLETE',
          'CANCELLED',
          'ERROR',
        ),
      },
      {
        type: FieldMetadataType.RAW_JSON,
        name: 'progress',
        label: 'Progress',
        icon: 'IconChartArrows',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'resultCount',
        label: 'Result Count',
        icon: 'IconListNumbers',
      },
      {
        type: FieldMetadataType.DATE_TIME,
        name: 'startedAt',
        label: 'Started At',
        icon: 'IconPlayerPlay',
      },
      {
        type: FieldMetadataType.DATE_TIME,
        name: 'completedAt',
        label: 'Completed At',
        icon: 'IconCheck',
      },
    ],
    relations: [
      {
        name: 'partnerTrack',
        label: 'Partner Track',
        icon: 'IconRoute',
        targetObjectName: 'partnerTrack',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Discovery Runs',
        targetFieldIcon: 'IconPlayerPlay',
      },
      {
        name: 'createdByMember',
        label: 'Created By',
        icon: 'IconUserCircle',
        targetObjectName: 'workspaceMember',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Discovery Runs',
        targetFieldIcon: 'IconPlayerPlay',
      },
    ],
    calendarFieldName: 'startedAt',
  },
  {
    object: {
      nameSingular: 'partnerCandidate',
      namePlural: 'partnerCandidates',
      labelSingular: 'Partner Candidate',
      labelPlural: 'Partner Candidates',
      description: 'Candidate result returned by discovery run',
      icon: 'IconBuildingFactory2',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.TEXT,
        name: 'entityUrl',
        label: 'Entity URL',
        icon: 'IconLink',
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'entityType',
        label: 'Entity Type',
        icon: 'IconUsersGroup',
        options: asSelectOptions('COMPANY', 'PERSON'),
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'displayName',
        label: 'Display Name',
        icon: 'IconTextCaption',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'companyDomain',
        label: 'Company Domain',
        icon: 'IconWorld',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'fitScore',
        label: 'Fit Score',
        icon: 'IconPercentage',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'confidence',
        label: 'Confidence',
        icon: 'IconShieldCheck',
      },
      {
        type: FieldMetadataType.SELECT,
        name: 'gateStatus',
        label: 'Gate Status',
        icon: 'IconFilter',
        options: asSelectOptions('QUALIFIED', 'DISQUALIFIED', 'EXCLUDED'),
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'gateReason',
        label: 'Gate Reason',
        icon: 'IconAlertCircle',
      },
      {
        type: FieldMetadataType.DATE_TIME,
        name: 'receivedAt',
        label: 'Received At',
        icon: 'IconCalendarTime',
      },
    ],
    relations: [
      {
        name: 'discoveryRun',
        label: 'Discovery Run',
        icon: 'IconPlayerPlay',
        targetObjectName: 'discoveryRun',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Candidates',
        targetFieldIcon: 'IconBuildingFactory2',
      },
    ],
  },
  {
    object: {
      nameSingular: 'checkEvaluation',
      namePlural: 'checkEvaluations',
      labelSingular: 'Check Evaluation',
      labelPlural: 'Check Evaluations',
      description: 'Per-check evaluation result for a candidate',
      icon: 'IconChecklist',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.SELECT,
        name: 'status',
        label: 'Status',
        icon: 'IconCircleCheck',
        options: asSelectOptions('MATCH', 'NO_MATCH', 'UNCLEAR'),
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'reasoningMd',
        label: 'Reasoning Markdown',
        icon: 'IconFileDescription',
      },
      {
        type: FieldMetadataType.RAW_JSON,
        name: 'sources',
        label: 'Sources',
        icon: 'IconLink',
      },
      {
        type: FieldMetadataType.NUMBER,
        name: 'contribution',
        label: 'Contribution',
        icon: 'IconPercentage',
      },
    ],
    relations: [
      {
        name: 'partnerCandidate',
        label: 'Partner Candidate',
        icon: 'IconBuildingFactory2',
        targetObjectName: 'partnerCandidate',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Check Evaluations',
        targetFieldIcon: 'IconChecklist',
      },
      {
        name: 'trackCheck',
        label: 'Track Check',
        icon: 'IconChecklist',
        targetObjectName: 'trackCheck',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Evaluations',
        targetFieldIcon: 'IconChecklist',
      },
    ],
  },
  {
    object: {
      nameSingular: 'enrichmentEvaluation',
      namePlural: 'enrichmentEvaluations',
      labelSingular: 'Enrichment Evaluation',
      labelPlural: 'Enrichment Evaluations',
      description: 'Per-enrichment extracted value for a candidate',
      icon: 'IconTablePlus',
      isRemote: false,
    },
    fields: [
      {
        type: FieldMetadataType.TEXT,
        name: 'valueText',
        label: 'Value',
        icon: 'IconTextCaption',
      },
      {
        type: FieldMetadataType.TEXT,
        name: 'reasoningMd',
        label: 'Reasoning Markdown',
        icon: 'IconFileDescription',
      },
      {
        type: FieldMetadataType.RAW_JSON,
        name: 'sources',
        label: 'Sources',
        icon: 'IconLink',
      },
    ],
    relations: [
      {
        name: 'partnerCandidate',
        label: 'Partner Candidate',
        icon: 'IconBuildingFactory2',
        targetObjectName: 'partnerCandidate',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Enrichment Evaluations',
        targetFieldIcon: 'IconTablePlus',
      },
      {
        name: 'trackEnrichment',
        label: 'Track Enrichment',
        icon: 'IconTablePlus',
        targetObjectName: 'trackEnrichment',
        relationType: RelationType.MANY_TO_ONE,
        targetFieldLabel: 'Evaluations',
        targetFieldIcon: 'IconTablePlus',
      },
    ],
  },
];
